#!/usr/bin/python
# -*- coding: utf-8 -*-


#MICAH BECK
#NOV 2 2021


from alphasign import *
import time
from time import sleep
from datetime import date
from datetime import datetime
import os
import subprocess
import requests
import atexit

dev = AlphaSign()

dev.roll_right(AMBER + BOLD + "October" + "          ")
time.sleep(0.10) #wait


